/**
 * Created by Administrator on 2018/2/6.
 */
var allImgData=[
    /*人物移动*/
    "img/zz_s0.png",
    "img/zz_s1.png",
    "img/zz_s2.png",
    "img/zz_s3.png",
    /*人物拖动*/
    "img/zz_s4.png",
    "img/zz_s5.png",
    "img/zz_s6.png",
    /*人物失败*/
    "img/zz_s7.png",
    /*钩子*/
    "img/gz/s8.png",
    "img/bg/startBg.jpg",
];
var userImg=[
    /*人物移动*/
    "img/zz_s0.png",
    "img/zz_s1.png",
    "img/zz_s2.png",
    "img/zz_s3.png",
    /*人物拖动*/
    "img/zz_s4.png",
    "img/zz_s5.png",
    "img/zz_s6.png",
    /*人物失败*/
    "img/zz_s7.png",
    /*钩子*/
    "img/gz/s8.png"
];
var gsImgInfo=[
    [
        [
            /*黄金*/
            "img/gold/hj1/s91.png",
            "img/gold/hj1/s92.png",
            "img/gold/hj1/s93.png",
            "img/gold/hj1/s94.png",
            "img/gold/hj2/s101.png",
            "img/gold/hj2/s102.png",
            "img/gold/hj2/s103.png",
            "img/gold/hj2/s104.png",
            "img/bg/bgO.jpg",
            "img/stone/s13.png",
            "img/stone/s14.png",
            "img/stone/s15.png",
            "img/goods/addNum.png"
        ],
        [
            {
                nowPush:true,
                x:0,
                y:0,
                w:500,
                h:800,
                img:METHOD.createImg( "img/bg/bgO.jpg")
            },
            {
                x:100,
                y:700,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
            
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:20,
                angle:190,
                y:680,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
            
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:400,
                y:500,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
            
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:250,
                y:700,
                w:72,
                h:72,
                angle:45,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
            
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:100,
                y:500,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },
            {
                stonge:2.5,
                x:350,
                y:300,
                w:105,
                h:105,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:120,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },
            {
                stonge:1.5,
                x:0,
                y:500,
                angle:30,
                w:72,
                h:72,
                addNum:5,
                img:METHOD.createImg("img/stone/s13.png")
            },
            {
                stonge:1.5,
                x:250,
                y:500,
                angle:160,
                w:72,
                h:72,
                addNum:5,
                img:METHOD.createImg("img/stone/s13.png")
            },
            {
                stonge:1.5,
                x:200,
                y:410,
                angle:120,
                w:72,
                h:72,
                addNum:5,
                img:METHOD.createImg("img/stone/s13.png")
            },
            {
                stonge:1.8,
                x:20,
                y:300,
                angle:30,
                w:105,
                h:105,
                addNum:8,
                img:METHOD.createImg("img/stone/s14.png")
            },
            {
                stonge:3.5,
                x:350,
                y:600,
                angle:30,
                w:141,
                h:141,
                addNum:10,
                img:METHOD.createImg("img/stone/s15.png")
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addNum.png"),
                w:40,
                h:30,
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            }
        ],
        100,//过关分数
        100//当前关数的时间 单位s
    ],
    [
        [
            /*黄金*/
            "img/gold/hj1/s91.png",
            "img/gold/hj1/s92.png",
            "img/gold/hj1/s93.png",
            "img/gold/hj1/s94.png",
            "img/gold/hj2/s101.png",
            "img/gold/hj2/s102.png",
            "img/gold/hj2/s103.png",
            "img/gold/hj2/s104.png",
            "img/bg/bgO.jpg",
            "img/stone/s13.png",
            "img/stone/s14.png",
            "img/stone/s15.png",
            "img/goods/addNum.png",
            "img/diamond/1083.png"
        ],
        [
            {
                nowPush:true,
                x:0,
                y:0,
                w:500,
                h:800,
                img:METHOD.createImg( "img/bg/bgO.jpg")
            },
            {
                x:220,
                y:600,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
            
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:20,
                angle:190,
                y:680,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
            
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                stonge:3.5,
                x:150,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:30,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                x:218,
                y:317,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:250,
                y:700,
                w:72,
                h:72,
                angle:45,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
            
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:100,
                y:500,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },
            {
                stonge:2.5,
                x:350,
                y:300,
                w:105,
                h:105,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:120,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },
            {
                stonge:1.5,
                x:0,
                y:500,
                angle:30,
                w:72,
                h:72,
                addNum:5,
                img:METHOD.createImg("img/stone/s13.png")
            },
            {
                stonge:1.5,
                x:250,
                y:500,
                angle:160,
                w:72,
                h:72,
                addNum:5,
                img:METHOD.createImg("img/stone/s13.png")
            },
            {
                stonge:1.5,
                x:200,
                y:410,
                angle:120,
                w:72,
                h:72,
                addNum:5,
                img:METHOD.createImg("img/stone/s13.png")
            },
            {
                stonge:1.8,
                x:20,
                y:300,
                angle:30,
                w:105,
                h:105,
                addNum:8,
                img:METHOD.createImg("img/stone/s14.png")
            },
            {
                stonge:3.5,
                x:350,
                y:600,
                angle:30,
                w:141,
                h:141,
                addNum:10,
                img:METHOD.createImg("img/stone/s15.png")
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addNum.png"),
                w:40,
                h:30,
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            }
        ],
        150,//过关分数
        100//当前关数的时间 单位s
    ],
    [
        [
            /*黄金*/
            "img/gold/hj1/s91.png",
            "img/gold/hj1/s92.png",
            "img/gold/hj1/s93.png",
            "img/gold/hj1/s94.png",
            "img/gold/hj2/s101.png",
            "img/gold/hj2/s102.png",
            "img/gold/hj2/s103.png",
            "img/gold/hj2/s104.png",
            "img/bg/bgO.jpg",
            "img/stone/s13.png",
            "img/stone/s14.png",
            "img/stone/s15.png",
            "img/goods/addNum.png",
            "img/diamond/1083.png",
            "img/diamond/1093.png"
        ],
        [
            {
                nowPush:true,
                x:0,
                y:0,
                w:500,
                h:800,
                img:METHOD.createImg( "img/bg/bgO.jpg")
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addNum.png"),
                w:40,
                h:30,
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            },
            {
                x:220,
                y:600,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:30,
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:370,
                y:520,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },
            {
                stonge:3.5,
                x:350,
                y:250,
                angle:30,
                w:141,
                h:141,
                addNum:10,
                img:METHOD.createImg("img/stone/s15.png")
            },
            {
                stonge:1.8,
                x:20,
                y:280,
                angle:30,
                w:105,
                h:105,
                addNum:8,
                img:METHOD.createImg("img/stone/s14.png")
            },
            {
                stonge:1.5,
                x:200,
                y:250,
                angle:30,
                w:72,
                h:72,
                addNum:5,
                img:METHOD.createImg("img/stone/s13.png")
            },
            {
                stonge:4.5,
                x:150,
                y:370,
                angle:0,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:3.5,
                x:150,
                y:700,
                angle:80,
                w:36,
                h:36,
                addNum:30,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                stonge:3.5,
                x:20,
                y:680,
                angle:40,
                w:36,
                h:36,
                addNum:30,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                stonge:1.5,
                x:335,
                y:433,
                angle:75,
                w:72,
                h:72,
                addNum:5,
                img:METHOD.createImg("img/stone/s13.png")
            },
            {
                stonge:1.5,
                x:277,
                y:500,
                angle:60,
                w:72,
                h:72,
                addNum:5,
                img:METHOD.createImg("img/stone/s13.png")
            },
            {
                x:208,
                y:400,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:30,
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            
            {
                x:100,
                y:500,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },
            {
                x:381,
                y:664,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },
            
            {
                stonge:1.5,
                x:64,
                y:420,
                angle:30,
                w:72,
                h:72,
                addNum:5,
                img:METHOD.createImg("img/stone/s13.png")
            }
        ],
        200,//过关分数
        100//当前关数的时间 单位s
    ],
    [
        [
            /*黄金*/
            "img/gold/hj1/s91.png",
            "img/gold/hj1/s92.png",
            "img/gold/hj1/s93.png",
            "img/gold/hj1/s94.png",
            "img/gold/hj2/s101.png",
            "img/gold/hj2/s102.png",
            "img/gold/hj2/s103.png",
            "img/gold/hj2/s104.png",
            "img/bg/bgT.jpg",
            "img/stone/s13.png",
            "img/stone/s14.png",
            "img/stone/s15.png",
            "img/goods/addNum.png",
            "img/goods/addTime.png",
            "img/diamond/1083.png",
            "img/diamond/1093.png",
            "img/diamond/1113.png"
        ],
        [
            {
                nowPush:true,
                x:0,
                y:0,
                w:500,
                h:800,
                img:METHOD.createImg( "img/bg/bgT.jpg")
            },
            {
                stonge:4.5,
                x:150,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:3.5,
                x:200,
                y:680,
                angle:60,
                w:36,
                h:36,
                addNum:30,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                stonge:5.5,
                x:300,
                y:750,
                angle:75,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            {
                stonge:1.5,
                x:200,
                y:300,
                angle:30,
                w:72,
                h:72,
                addNum:5,
                img:METHOD.createImg("img/stone/s13.png")
            },
            {
                stonge:1.5,
                x:20,
                y:300,
                angle:60,
                w:72,
                h:72,
                addNum:5,
                img:METHOD.createImg("img/stone/s13.png")
            },
            {
                stonge:1.5,
                x:350,
                y:270,
                angle:100,
                w:72,
                h:72,
                addNum:5,
                img:METHOD.createImg("img/stone/s13.png")
            },
            {
                x:220,
                y:550,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:30,
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:20,
                y:500,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:30,
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:400,
                y:500,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:60,
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            
            {
                x:100,
                y:570,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },
            
            {
                x:150,
                y:400,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },

            {
                x:350,
                y:350,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },

            {
                stonge:3.5,
                x:20,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:30,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                stonge:3.5,
                x:440,
                y:750,
                angle:0,
                w:36,
                h:36,
                addNum:30,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addNum.png"),
                w:40,
                h:30,
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                createTime:15,
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addTime.png"),
                w:38,
                h:40,
                createTime:80,
                changeVal:"10",
                getGoods:function(centerObj){
                    centerObj.nowTime-=10;
                },
                changeKey:"",
                changeValTxt:"时间增加",
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            }
        ],
        250,//过关分数
        100//当前关数的时间 单位s
    ],
    [
        [
            /*黄金*/
            "img/gold/hj1/s91.png",
            "img/gold/hj1/s92.png",
            "img/gold/hj1/s93.png",
            "img/gold/hj1/s94.png",
            "img/gold/hj2/s101.png",
            "img/gold/hj2/s102.png",
            "img/gold/hj2/s103.png",
            "img/gold/hj2/s104.png",
            "img/bg/bgT.jpg",
            "img/stone/s13.png",
            "img/stone/s14.png",
            "img/stone/s15.png",
            "img/goods/addNum.png",
            "img/goods/addTime.png",
            "img/diamond/1083.png",
            "img/diamond/1093.png",
            "img/diamond/1113.png",
            "img/crystal/1009.png",
            "img/crystal/1019.png",
            "img/crystal/1029.png"
        ],
        [
            {
                nowPush:true,
                x:0,
                y:0,
                w:500,
                h:800,
                img:METHOD.createImg( "img/bg/bgT.jpg")
            },
            {
                stonge:4.5,
                x:80,
                y:300,
                angle:0,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:6.5,
                x:150,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
            {
                stonge:4.5,
                x:30,
                y:550,
                angle:72,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:3.5,
                x:200,
                y:680,
                angle:60,
                w:36,
                h:36,
                addNum:30,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                stonge:5.5,
                x:300,
                y:750,
                angle:75,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            
            {
                x:220,
                y:450,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:35,
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:20,
                y:400,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:20,
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:400,
                y:400,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:50,
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            
            {
                x:100,
                y:470,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:95,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },
            
            {
                x:150,
                y:300,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },

            {
                x:350,
                y:250,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },

            {
                stonge:3.5,
                x:20,
                y:654,
                angle:0,
                w:36,
                h:36,
                addNum:30,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                stonge:3.5,
                x:440,
                y:650,
                angle:0,
                w:36,
                h:36,
                addNum:30,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addNum.png"),
                w:40,
                h:30,
                changeVal:"10",
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addTime.png"),
                w:38,
                h:40,
                createTime:80,
                changeVal:"10",
                getGoods:function(centerObj){
                    centerObj.nowTime-=10;
                },
                changeKey:"",
                changeValTxt:"时间增加",
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            }
        ],
        300,//过关分数
        100//当前关数的时间 单位s
    ],
    [
        [
            /*黄金*/
            "img/gold/hj1/s91.png",
            "img/gold/hj1/s92.png",
            "img/gold/hj1/s93.png",
            "img/gold/hj1/s94.png",
            "img/gold/hj2/s101.png",
            "img/gold/hj2/s102.png",
            "img/gold/hj2/s103.png",
            "img/gold/hj2/s104.png",
            "img/bg/bgT.jpg",
            "img/stone/s13.png",
            "img/stone/s14.png",
            "img/stone/s15.png",
            "img/goods/addNum.png",
            "img/goods/addTime.png",
            "img/diamond/1083.png",
            "img/diamond/1093.png",
            "img/diamond/1113.png",
            "img/crystal/1009.png",
            "img/crystal/1019.png",
            "img/crystal/1029.png"
        ],
        [
            {
                nowPush:true,
                x:0,
                y:0,
                w:500,
                h:800,
                img:METHOD.createImg( "img/bg/bgT.jpg")
            },
            {
                stonge:4.5,
                x:80,
                y:300,
                angle:0,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:6.5,
                x:150,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
            {
                stonge:4.5,
                x:30,
                y:550,
                angle:72,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:3.5,
                x:200,
                y:680,
                angle:60,
                w:36,
                h:36,
                addNum:30,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                stonge:5.5,
                x:300,
                y:750,
                angle:75,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            
            {
                x:220,
                y:450,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:35,
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:20,
                y:400,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:20,
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            {
                x:241,
                y:581,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:25,
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
                {
                    x:350,
                    y:550,
                    w:105,
                    h:105,
                    stonge:2.5,
                    addNum:25,
                    method2:[
                        {
                            name:"changeAnimate"
                        }
                    ],
                    angle:80,
                    imgArr:[
                        METHOD.createImg("img/gold/hj2/s101.png"),
                        METHOD.createImg("img/gold/hj2/s102.png"),
                        METHOD.createImg("img/gold/hj2/s103.png"),
                        METHOD.createImg("img/gold/hj2/s104.png")
                    ]
                },
            {
                x:400,
                y:400,
                w:72,
                h:72,
                stonge:2.0,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:50,
                imgArr:[
                    METHOD.createImg("img/gold/hj1/s91.png"),
                    METHOD.createImg("img/gold/hj1/s92.png"),
                    METHOD.createImg("img/gold/hj1/s93.png"),
                    METHOD.createImg("img/gold/hj1/s94.png")
                ],
                addNum:15
            },
            
            {
                x:100,
                y:470,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:95,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },
            
            {
                x:150,
                y:300,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },

            {
                x:350,
                y:250,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },

         
            {
                stonge:4.5,
                x:20,
                y:720,
                angle:0,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:5.5,
                x:250,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            {
                stonge:6.5,
                x:450,
                y:750,
                angle:30,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addNum.png"),
                w:40,
                h:30,
                changeVal:10,
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addTime.png"),
                w:38,
                h:40,
                createTime:80,
                changeVal:"10",
                getGoods:function(centerObj){
                    centerObj.nowTime-=10;
                },
                changeKey:"",
                changeValTxt:"时间增加",
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            }
        ],
        350,//过关分数
        100//当前关数的时间 单位s
    ],
    [
        [
            /*黄金*/
            "img/gold/hj1/s91.png",
            "img/gold/hj1/s92.png",
            "img/gold/hj1/s93.png",
            "img/gold/hj1/s94.png",
            "img/gold/hj2/s101.png",
            "img/gold/hj2/s102.png",
            "img/gold/hj2/s103.png",
            "img/gold/hj2/s104.png",
            "img/bg/bgTH.jpg",
            "img/stone/s13.png",
            "img/stone/s14.png",
            "img/stone/s15.png",
            "img/goods/addNum.png",
            "img/goods/addTime.png",
            "img/diamond/1083.png",
            "img/diamond/1093.png",
            "img/diamond/1113.png",
            "img/crystal/1009.png",
            "img/crystal/1019.png",
            "img/crystal/1029.png"
        ],
        [
            {
                nowPush:true,
                x:0,
                y:0,
                w:500,
                h:800,
                img:METHOD.createImg("img/bg/bgTH.jpg")
            },
            {
                stonge:4.5,
                x:80,
                y:300,
                angle:0,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:6.5,
                x:150,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
            {
                stonge:4.5,
                x:30,
                y:550,
                angle:72,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:4.5,
                x:450,
                y:500,
                angle:72,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:4.5,
                x:280,
                y:550,
                angle:72,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:3.5,
                x:200,
                y:680,
                angle:60,
                w:36,
                h:36,
                addNum:30,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                stonge:5.5,
                x:300,
                y:750,
                angle:75,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            {
                stonge:7.5,
                x:450,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:65,
                img:METHOD.createImg( "img/crystal/1019.png")
            },
      
       
            {
                stonge:6.5,
                x:100,
                y:650,
                angle:0,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
                {
                    x:350,
                    y:550,
                    w:105,
                    h:105,
                    stonge:2.5,
                    addNum:25,
                    method2:[
                        {
                            name:"changeAnimate"
                        }
                    ],
                    angle:80,
                    imgArr:[
                        METHOD.createImg("img/gold/hj2/s101.png"),
                        METHOD.createImg("img/gold/hj2/s102.png"),
                        METHOD.createImg("img/gold/hj2/s103.png"),
                        METHOD.createImg("img/gold/hj2/s104.png")
                    ]
                },
    
            
            {
                x:100,
                y:470,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:95,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },
            
            {
                x:150,
                y:300,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },

            {
                x:350,
                y:250,
                w:105,
                h:105,
                stonge:2.5,
                addNum:25,
                method2:[
                    {
                        name:"changeAnimate"
                    }
                ],
                angle:80,
                imgArr:[
                    METHOD.createImg("img/gold/hj2/s101.png"),
                    METHOD.createImg("img/gold/hj2/s102.png"),
                    METHOD.createImg("img/gold/hj2/s103.png"),
                    METHOD.createImg("img/gold/hj2/s104.png")
                ]
            },

         
            {
                stonge:4.5,
                x:20,
                y:720,
                angle:0,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:5.5,
                x:250,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            {
                stonge:6.5,
                x:450,
                y:750,
                angle:30,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addNum.png"),
                w:40,
                h:30,
                changeVal:10,
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addTime.png"),
                w:38,
                h:40,
                createTime:80,
                changeVal:"10",
                getGoods:function(centerObj){
                    centerObj.nowTime-=10;
                },
                changeKey:"",
                changeValTxt:"时间增加",
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            }
        ],
        400,//过关分数
        100//当前关数的时间 单位s
    ],
    [
        [
            /*黄金*/
            "img/gold/hj1/s91.png",
            "img/gold/hj1/s92.png",
            "img/gold/hj1/s93.png",
            "img/gold/hj1/s94.png",
            "img/gold/hj2/s101.png",
            "img/gold/hj2/s102.png",
            "img/gold/hj2/s103.png",
            "img/gold/hj2/s104.png",
            "img/bg/bgTH.jpg",
            "img/stone/s13.png",
            "img/stone/s14.png",
            "img/stone/s15.png",
            "img/goods/addNum.png",
            "img/goods/addTime.png",
            "img/diamond/1083.png",
            "img/diamond/1093.png",
            "img/diamond/1113.png",
            "img/crystal/1009.png",
            "img/crystal/1019.png",
            "img/crystal/1029.png"
        ],
        [
            {
                nowPush:true,
                x:0,
                y:0,
                w:500,
                h:800,
                img:METHOD.createImg("img/bg/bgTH.jpg")
            },
            {
                stonge:4.5,
                x:80,
                y:300,
                angle:0,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:6.5,
                x:150,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
            {
                stonge:4.5,
                x:30,
                y:550,
                angle:72,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:4.5,
                x:450,
                y:500,
                angle:72,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:4.5,
                x:280,
                y:550,
                angle:72,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:3.5,
                x:200,
                y:680,
                angle:60,
                w:36,
                h:36,
                addNum:30,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                stonge:5.5,
                x:300,
                y:750,
                angle:75,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            {
                stonge:7.5,
                x:450,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:65,
                img:METHOD.createImg( "img/crystal/1019.png")
            },
      
       
            {
                stonge:6.5,
                x:100,
                y:650,
                angle:0,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
         
    
            
        

         
            {
                stonge:4.5,
                x:20,
                y:720,
                angle:0,
                w:36,
                h:36,
                addNum:40,
                img:METHOD.createImg("img/diamond/1093.png")
            },
            {
                stonge:5.5,
                x:250,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            {
                stonge:6.5,
                x:450,
                y:750,
                angle:30,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addNum.png"),
                w:40,
                h:30,
                changeVal:10,
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            },
            {
                stonge:3.5,
                x:150,
                y:330,
                angle:35,
                w:36,
                h:36,
                addNum:20,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                stonge:3.5,
                x:20,
                y:280,
                angle:20,
                w:36,
                h:36,
                addNum:20,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                stonge:5.5,
                x:400,
                y:450,
                angle:50,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            {
                stonge:5.5,
                x:350,
                y:550,
                angle:340,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            {
                stonge:5.5,
                x:450,
                y:650,
                angle:0,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            {
                stonge:3.5,
                x:250,
                y:360,
                angle:30,
                w:36,
                h:36,
                addNum:20,
                img:METHOD.createImg("img/diamond/1083.png")
            },
            {
                stonge:6.5,
                x:150,
                y:750,
                angle:0,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addTime.png"),
                w:38,
                h:40,
                createTime:80,
                changeVal:"20",
                getGoods:function(centerObj){
                    centerObj.nowTime-=20;
                },
                changeKey:"",
                changeValTxt:"时间增加",
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            }
        ],
        450,//过关分数
        100//当前关数的时间 单位s
    ],
    [
        [
            /*黄金*/
            "img/gold/hj1/s91.png",
            "img/gold/hj1/s92.png",
            "img/gold/hj1/s93.png",
            "img/gold/hj1/s94.png",
            "img/gold/hj2/s101.png",
            "img/gold/hj2/s102.png",
            "img/gold/hj2/s103.png",
            "img/gold/hj2/s104.png",
            "img/bg/bgTH.jpg",
            "img/stone/s13.png",
            "img/stone/s14.png",
            "img/stone/s15.png",
            "img/goods/addNum.png",
            "img/goods/addTime.png",
            "img/diamond/1083.png",
            "img/diamond/1093.png",
            "img/diamond/1113.png",
            "img/crystal/1009.png",
            "img/crystal/1019.png",
            "img/crystal/1029.png"
        ],
        [
            {
                nowPush:true,
                x:0,
                y:0,
                w:500,
                h:800,
                img:METHOD.createImg("img/bg/bgTH.jpg")
            },
        
            {
                stonge:6.5,
                x:150,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
            {
                stonge:5.5,
                x:300,
                y:750,
                angle:75,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            {
                stonge:7.5,
                x:450,
                y:700,
                angle:60,
                w:36,
                h:36,
                addNum:65,
                img:METHOD.createImg( "img/crystal/1019.png")
            },
      
            {
                stonge:7.5,
                x:20,
                y:700,
                angle:20,
                w:36,
                h:36,
                addNum:65,
                img:METHOD.createImg( "img/crystal/1019.png")
            },
            {
                stonge:6.5,
                x:200,
                y:750,
                angle:45,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
            {
                stonge:7.5,
                x:30,
                y:650,
                angle:30,
                w:36,
                h:36,
                addNum:65,
                img:METHOD.createImg( "img/crystal/1019.png")
            },
            {
                stonge:6.5,
                x:100,
                y:650,
                angle:0,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
         
    
            
        

            {
                stonge:5.5,
                x:250,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            {
                stonge:6.5,
                x:450,
                y:750,
                angle:30,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addNum.png"),
                w:40,
                h:30,
                changeVal:15,
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            },

      
            {
                stonge:5.5,
                x:400,
                y:450,
                angle:50,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            {
                stonge:5.5,
                x:350,
                y:550,
                angle:340,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
            {
                stonge:5.5,
                x:450,
                y:650,
                angle:0,
                w:36,
                h:36,
                addNum:50,
                img:METHOD.createImg("img/diamond/1113.png")
            },
     
            {
                stonge:9.5,
                x:20,
                y:750,
                angle:0,
                w:36,
                h:36,
                addNum:75,
                img:METHOD.createImg( "img/crystal/1029.png")
            },
            {
                stonge:6.5,
                x:150,
                y:750,
                angle:0,
                w:36,
                h:36,
                addNum:60,
                img:METHOD.createImg( "img/crystal/1009.png")
            },
            {
                stonge:7.5,
                x:450,
                y:700,
                angle:0,
                w:36,
                h:36,
                addNum:65,
                img:METHOD.createImg( "img/crystal/1019.png")
            },
            {
                type:"goods",
                shadowColor:"rgba(255,255,0,1)",
                shadowBlur:10,
                img:METHOD.createImg("img/goods/addTime.png"),
                w:38,
                h:40,
                createTime:80,
                changeVal:"20",
                getGoods:function(centerObj){
                    centerObj.nowTime-=20;
                },
                changeKey:"",
                changeValTxt:"时间增加",
                method:[
                    {
                        name:"isCreate"
                    },
                    {
                        name:"moveY",
                        arguments:"set=>centerObj"
                    }
                ],
                method3:[
                    {
                        name:"timeInfo"
                    }
                ]
            }
        ],
        550,//过关分数
        100//当前关数的时间 单位s
    ]
];